data_container:
  image: ruby:2.3
  volumes:
    - /usr/local/bundle
  command: /bin/sh

app: &default
  image: ruby:2.3
  volumes:
    - .:/app
  volumes_from:
    - data_container
  working_dir: /app
  environment:
    VCAP_SERVICES: |
      {
          "alchemy_api": [ { "credentials": { "apikey": "98cfcb9d595027b5278130e692f69019b9587012" } } ]
      }
