data_container:
  image: ruby:2.3
  volumes:
    - /usr/local/bundle
  command: /bin/sh

app: &default
  image: ruby:2.3
  volumes:
    - .:/app
  volumes_from:
    - data_container
  ports:
    - 5000:5000
  working_dir: /app
